name: Manually trigger delivery
on: [workflow_dispatch]

jobs:
  manual:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deliver
        run: |
          curl -s "https://raw.githubusercontent.com/eduardostuart/paperboy/main/scripts/install.sh" | bash
          ./paperboy deliver ${{ secrets.MAIL_TO }} ./subs.txt ./template.hbs ./template_text.hbs
        env:
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_FROM: ${{ secrets.SMTP_FROM }}
          MAIL_TO: ${{ secrets.MAIL_TO }}
          # EMAIL_SUBJECT: "Paperboy - Today's news"
